// packages/next-openapi-gen/templates/init/ui/sveltekit/stoplight.svelte
<svelte:head>
  <title>API Documentation</title>
  <link rel="stylesheet" href="https://unpkg.com/@stoplight/elements/styles.min.css">
  <script src="https://unpkg.com/@stoplight/elements/web-components.min.js"></script>
</svelte:head>

<elements-api apiDescriptionUrl="/__NEXT_OPENAPI_GEN_OUTPUT_FILE__" router="hash"></elements-api>

// packages/openapi-init/templates/init/ui/tanstack/stoplight.tsx
import { createFileRoute } from "@tanstack/react-router";
import { API } from "@stoplight/elements";
import "@stoplight/elements/styles.min.css";

export const Route = createFileRoute("__NEXT_OPENAPI_GEN_ROUTE_PATH__")({
  component: ApiDocsPage,
});

function ApiDocsPage() {
  return (
    <section style={{ height: "100vh" }}>
      <API apiDescriptionUrl="/__NEXT_OPENAPI_GEN_OUTPUT_FILE__" />
    </section>
  );
}
